{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logd.serviceAccountName" . }}
  labels:
{{ include "logd.labels" . | nindent 4 }}
{{- end -}}
