apiVersion: v1
kind: Service
metadata:
  name: {{ include "logd.fullname" . }}
  labels:
    {{- include "logd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: logd
      protocol: TCP
      name: logd
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "logd.selectorLabels" . | nindent 4 }}
