# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: logd
    env:
      - CGO_ENABLED=0
    main: ./cmd/logd
    binary: logd
    ldflags: -s -w -X main.ReleaseVersion={{.Version}} -X main.ReleaseCommit={{.ShortCommit}} -X main.ReleaseDate={{.Date}}
  - id: log-cli
    env:
      - CGO_ENABLED=0
    main: ./cmd/log-cli
    binary: log-cli
    ldflags: -s -w -X main.ReleaseVersion={{.Version}} -X main.ReleaseCommit={{.ShortCommit}} -X main.ReleaseDate={{.Date}}

dockers:
- dockerfile: .goreleaser/Dockerfile
  binaries:
    - logd
  image_templates:
  - "logd/logd:latest"
  - "logd/logd:{{ .Major }}"
  - "logd/logd:{{ .Major }}.{{ .Minor }}"
  - "logd/logd:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{.Version}}"
  - "--label=org.label-schema.name={{.ProjectName}}"
- dockerfile: .goreleaser/Dockerfile.cli
  binaries:
    - log-cli
  image_templates:
  - "logd/log-cli:latest"
  - "logd/log-cli:{{ .Major }}"
  - "logd/log-cli:{{ .Major }}.{{ .Minor }}"
  - "logd/log-cli:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{.Version}}"
  - "--label=org.label-schema.name={{.ProjectName}}"

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - README.md
    - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
