# vi: ft=dockerfile
FROM golang:1.13

RUN mkdir /logd
WORKDIR /logd

COPY go.mod go.sum Makefile /logd/
RUN set -ex; \
    go mod download \
    && make deps \
    && make clean

COPY . /logd

CMD ["make", "ci"]
